// BuildInfo.swift
// Auto-generated at build time - DO NOT EDIT MANUALLY
// This file is regenerated by `make build` or `make build-debug`

/// Indicates if this is a development build (not from a clean release tag)
let isDevelopmentBuild = true

/// Short git commit hash (empty for release builds)
let gitCommitHash = "1e4fc02"
