name: Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version: pr-${{ github.event.pull_request.number }}
      upload_artifacts: true
